# Generated by Django 5.2.6 on 2025-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
