# Generated by Django 5.2.6 on 2025-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0002_yangiliklar_image_alter_yangiliklar_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('page_count', models.IntegerField()),
                ('author', models.CharField(max_length=256)),
            ],
        ),
    ]
